### ISSUE TITLE
DNA Lab: Accessioning and Assessment Workflow Touch-Up

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#255]
Feedback provided by Tracie:

DNA Lab -  Accessioning Workflow:

- [X] Under Ingest leading 0 needs to be required for external 2D barcodes **- Finished by Lee**  #251 
- [X] Under Ingest BC Type needs to be a required field **- Finished by Lee** #254 
- [X] Under Ingest Review we would like library type picklist shortened to only DNA Lab library types **- Finished by Lee** #254
- [x] We would like a Sample Name column in all protocols so we don’t have to click on the DNA name each time in order to map it to the sample name. #242 

 
 
DNA Lab - Assessment Workflow:

- [x] Assessment Kit Lot #, Assessment Kit Lot Barcode, Buffer EB Lot Barcode are currently under “Assessment Set Up” and it would flow better to have them moved to “Assessment Initial Data”
- Took the initiative to turn them into protocol fields
- [x] In “Assessment Set Up”  we would like a Technician column added so that we can assign to a specific person in the lab.  If it’s easier to provide a drop down menu of the people in the DNA Lab I can provide that. 
- Do we want to add an alert protocol action when assigned? Not right now.
- [x] We would like a Notes or Comment column in each protocol for oddities that may occur with samples
- [ ] We will need a Dry Down option added possibly in it’s own column as a check box?  It could default to no, but if we check yes then we would want to be able to input a volume that we want the technician to dry the sample down to.  This new volume changes the concentration and possibly the Dilution Factor.     We can discuss the best way to represent this when you are ready to work on this. #267

**Comment by billtell** [comment]
Maybe turn into a separate ticket?

- [ ] I also had a question about the time stamp.  I thought I remember something about it being automatic, but if it’s not we may want to add a Date Started or a Date Assigned column to a few of the protocols. #267
