### ISSUE TITLE
SC: Protocol/Workflow Additions/Cleanup/Bugfix

### ISSUE THREAD

**Issue by LMT337** [GTAC-MGI/GTAC-ESP-LIMS#363]
SC protocol updates, additions and bugfixes from 02/15/24 meeting. 
Fixes apply to 3 prime and 5 prime workflows and any duplicate protocols that are repeated in the workflow but have a higher iteration.

**Comment by LMT337** [comment]
- [x] cDNA Entity update species from NA to blank
- [x] Move 2D BC column from SC Lab: 3 prime cDNA Amplification Reaction Reagents to SC Lab: 3 prime cDNA CleanUp Reagents
>  2D BC column added to `SC Lab: 5 prime cDNA Amp CleanUp Reagents` as well.
- [x] In Agilent HS Run (con value / 1000) * 40 add value to Total NG yield col - fix broken expression (resolved in #243)
- [x] Add inheritance to billing values but hide cols in the 3/5 prime CDNA Barcode protocol(inheritance resolved in #374 and #375)
- [x] Add -lot# to SC Lab: 3 prime Dual SPRI Reagents and 5 prime col names
- [x] Remove 2D barcode from Qubit and Agilent protocols - Remaining volume expression needs to be fixed, hide storage location. (moving this to a new ticket for Remaining Volume tracking #377)
- [x] Dilutions - hide storage column
- [x] Create Dilutions workflow- implement data links
- [x] SC Lab: 3 v 3.1 GEX With Feature CellPlex-CRISPR - Becomes Sample protocol (resolved in #369)

**Comment by billtell** [comment]
- [ ] Create Dilutions hide storage stuff in sample protocol
