### ISSUE TITLE
SC Lab: Reagent tracking to start of each node - 3 Prime

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#388]
There has been a lot of redundant reagent lot # tracking that will try to get addressed by creating a Reagent Tracking protocol at the beginning of workflow node.  Will start in 3 prime to get a feel for how this may look. 

Will also drop some of the lot number columns that have been identified so far.

**Comment by billtell** [comment]
- [x] remove transferred supernatent cleanup lot # column - SC Lab: 3 prime Sample Feature Index PCR Mix Reagents
- [x] Remove Purified GEM-RT lot number and storage location -  SC Lab: 3 prime cDNA Amplification Reaction Reagents
- [x] Remove  2D Barcode, we would scan at the cDNA barcode step - SC Lab: 3 prime cDNA Amp CleanUp Reagents

**Comment by billtell** [comment]
- [x] 2D barcode not needed here - SC Lab: 3 prime Qubit and Agilent

**Comment by billtell** [comment]
**Workflows to remodel**
- [x] 3Prime cDNA
- [x] GEX LC
- [x] Feature LC

**Comment by billtell** [comment]
To comment out, then remove:
Feature:
- [x]  SC Lab: 3 prime Sample Feature Index PCR Mix Reagents
- [x]  SC Lab: 3 prime Post PCR Clean Up
GEX:
- [x]  SC Lab: 3 prime Fragmentation: End Repair and A-Tailing Reagents
- [x]  SC Lab: 3 prime Dual SPRI Reagents
- [x] SC Lab: 3 prime Adaptor Ligation Reagents
- [x] SC Lab: 3 prime Post Ligation Clean Up Reagent
- [x] SC Lab: 3 prime Sample Index PCR Mix Reagents
- [x] SC Lab: 3 prime Post PCR Clean Up
cDNA:
- [x] SC Lab: 3 prime GEM Generation and Barcoding reagents Lot Inventory
- [x] SC Lab: 3 prime Dyna Beads Cleanup Mix Reagents
- [x] SC Lab: 3 prime Elution solution I Reagents
- [x] SC Lab: 3 prime cDNA Amplification Reaction Reagents
- [x] SC Lab: 3 prime cDNA Amp CleanUp Reagents
