### ISSUE TITLE
SC Lab: Reagent tracking to start of each node - 5 Prime and Multiome

### ISSUE THREAD

**Issue by billtell** [GTAC-MGI/GTAC-ESP-LIMS#389]
Follow the example laid out in #388. 
Set Reagent tracking to the front of workflow nodes to reduce duplicate entries.

**Comment by billtell** [comment]
- Multiome
- [x]  SC Lab: Transposition - Move 2nd protocol's lot numbers to protocol fields is first
- [x]  SC Lab: Pre-Amp
- [x]  SC Lab: Multiome cDNA
- [x] SC Lab: Multiome GEX LC
- [x]  SC Lab: ATAC LC

**Comment by billtell** [comment]
- To comment out, then remove:
-  SC Lab: Transposition - Move 2nd protocol's lot numbers to protocol fields is first
- [x] SC Lab: Multiome Transposition and GEM Generation and Barcoding reagents Lot Inventory
- SC Lab: Pre-Amp
- [x] SC Lab: Multiome Post GEM Incubation Cleanup reagents Lot Inventory
- [x] SC Lab: Multiome Pre-AMP reagents Lot Inventory
- [x] SC Lab: Multiome Pre-Amp CleanUp Reagents
- SC Lab: Multiome cDNA
- [x] SC Lab: Multiome cDNA Amplification Reaction Reagents
- [x] SC Lab: Multiome cDNA Amp CleanUp Reagents
- SC Lab: Multiome GEX LC
- [x] SC Lab: Multiome Fragmentation: End Repair and A-Tailing Reagents
- [x] SC Lab: Multiome Dual SPRI Reagents
- [x] SC Lab: Multiome Adaptor Ligation Reagents
- [x] SC Lab: Multiome Post Ligation Clean Up Reagents
- [x] SC Lab: Multiome Sample Index PCR Mix Reagents
- [x] SC Lab: Multiome Post PCR Clean Up
- SC Lab: ATAC LC
- [x] SC Lab: Multiome ATAC Library reagents Lot Inventory
- [x] SC Lab: Multiome ATAC Library CleanUp Reagents

**Comment by billtell** [comment]
- [x] Multiome Reagent protocols added to workflows

**Comment by billtell** [comment]
Moved 3 Prime reagent tracking to protocol fields.

**Comment by billtell** [comment]
- To comment out, then remove:
- SC Lab: 5Prime cDNA
- [x] SC Lab: 5 prime GEM Generation and Barcoding Reagents Lot Inventory
- [x] SC Lab: 5 prime Dyna Beads Cleanup Mix Reagents
- [x] SC Lab: 5 prime Elution Solution I Reagent
- [x] SC Lab: 5 prime cDNA Amplification Reaction Reagents
- [x] SC Lab: 5 prime cDNA Amp CleanUp Reagents
- SC Lab: 5Prime Enrichment
- [x] SC Lab: 5 prime Target Enrichment 1 Reagents
- [x] SC Lab: 5 prime Post Enrichment 1 SPRI
- [x] SC Lab: 5 prime Target Enrichment 2 Reagents
- [x] SC Lab: 5 prime Post Enrichment 2 DUAL SPRI
- SC Lab: 5Prime Enrichment LC
- [x] SC Lab: 5 prime Fragmentation: End Repair and A-Tailing Reagents
- [x] SC Lab: 5 prime Dual SPRI Reagents
- [x] SC Lab: 5 prime Adaptor Ligation Reagents
- [x] SC Lab: 5 prime Post Ligation Clean Up Reagents
- [x] SC Lab: 5 prime Sample Index PCR Mix Reagents
- [x] SC Lab: 5 prime Post PCR Clean Up
- [x] SC Lab: 5 prime Post PCR Clean Up Reagents
- SC Lab: 5Prime Feature LC
- [x] SC Lab: 5 prime Sample Feature Index PCR Mix Reagents
- [x] SC Lab: 5 prime Post PCR Clean Up
- SC Lab: 5Prime GEX LC
- [x] SC Lab: 5 prime Fragmentation: End Repair and A-Tailing Reagents
- [x] SC Lab: 5 prime Dual SPRI Reagents
- [x] SC Lab: 5 prime Adaptor Ligation Reagents
- [x] SC Lab: 5 prime Post Ligation Clean Up Reagents
- [x] SC Lab: 5 prime Sample Index PCR Mix Reagents
- [x] SC Lab: 5 prime Post PCR Clean Up
- [x] SC Lab: 5 prime Post PCR Clean Up Reagents

**Comment by billtell** [comment]
Moved Multiome reagents to protocol fields

**Comment by billtell** [comment]
5 Prime workflow remodel
- [x] SC Lab: 5Prime cDNA
- [x] SC Lab: 5Prime Enrichment
- [x] SC Lab: 5Prime Enrichment LC
- [x] SC Lab: 5Prime Feature LC
- [ ] SC Lab: 5Prime GEX LC
